version: '3.8'

services:
  ochrona-keygen:
    image: alpine
    volumes:
      - ./crt:/crt
    entrypoint: bin/sh
    command: -c "apk add openssl && openssl req -nodes -new -x509 -keyout /crt/key.pem -out /crt/cert.pem -subj '/CN=localhost'"

  ochrona-nginx:
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./crt:/etc/nginx/crt
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ochrona-keygen
      - ochrona-backend
      - ochrona-frontend
    networks:
      - ochrona-network

  ochrona-db:
    image: postgres
    container_name: ochrona-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - ochrona-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 3s
      retries: 30

  ochrona-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ochrona-backend
    ports:
      - '3000:3000'
    networks:
      - ochrona-network
    depends_on:
      - ochrona-db
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthcheck']
      interval: 30s
      timeout: 3s
      retries: 3

  ochrona-frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    networks:
      - ochrona-network

networks:
  ochrona-network:
